config/routes.rb
Rails.application.routes.draw do

  root  'home#index' 
  
  resources :forms, only:[:index]
  get 'forms/find' => 'forms#find'
  resources :home, only:[:create,:new]
  get 'home/index'
  

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
 validates :subject,presence: true
  validates :email,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def index
  end

 def find
 @inquiry= Inquiry.where('name like ?',"%" + params[:serch_name] + "%")

 end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @inquiry = Inquiry.new
  end
  
  def create

  @inquiry = Inquiry.new(inquiry_params)
  if @inquiry.save
  redirect_to root_path
else
  redirect_to n_home_path
  end
end
  
  
  
  private
  
  def inquiry_params
    params.require(:inquiry).permit(:name,:body,:email,:subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/forms/find.html.erb
nameserh
<% @inquiry.each do |inquiry|%>
<%= inquiry.subject %>
<%= inquiry.name %>
<%= inquiry.email %>
<%= inquiry.body %>
<% end %>

app/views/forms/index.html.erb
<h1>Forms#index</h1>
<p>Find me in app/views/forms/index.html.erb</p>
<%= form_tag forms_find_path,:method=>'get' do %>
nameserch
<%= text_field_tag :serch_name %>
<%= submit_tag "search" %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= form_for @inquiry,:url => {:action => :create} do |f| %>


<%= f.label :body , "subject"%>
<%= f.text_field :subject %>
</br>
<%= f.label :name , "name"%>
<%= f.text_field :name %>
</br>
<%= f.label :body , "email"%>
<%= f.text_field :email %>
</br>
<%= f.label :body , "body"%>
<%= f.text_area :body %>
</br>
<%= f.submit "送信" %>
<% end %>
<%= link_to "serchname" , "forms"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubjectApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>